[tools]
node = "22.13.1"
zoxide = "latest"
fzf = "latest"
lazygit = "latest"
fd = "latest"
ripgrep = "latest"
deno = "latest"
bun = "latest"
jq = "latest"
stylua = "latest"
tmux = "latest"
imagemagick = "7.1.2-0"
bat = "latest"
delta = "latest"
chezmoi = "latest"
usage = "latest"

[settings]
experimental = true
# needed for compatibility with `uv`
idiomatic_version_file_enable_tools = ["python"]
