[tools]
node = "lts"
zoxide = "latest"
fzf = "latest"
go = "latest"
lazygit = "latest"
fd = "latest"
ripgrep = "latest"
deno = "latest"
bun = "latest"
jq = "latest"
stylua = "latest"

[settings]
experimental = true
