[tools]
node = "22.13.1"
zoxide = "latest"
fzf = "latest"
go = "latest"
lazygit = "latest"
fd = "latest"
ripgrep = "latest"
deno = "latest"
bun = "latest"
jq = "latest"
stylua = "latest"
zig = "0.13"
tmux = "latest"
java = "21.0.2"

[settings]
experimental = true
