os:
  # edit: "nvim --server $NVIM --remote-tab {{filename}}"
  edit: "nvr --remote-send '<C-\\><C-N><cmd>q<CR><cmd>lua vim.cmd(\"e \" .. {{filename}})<CR>'"

keybinding:
  universal:
    scrollUpMain-alt1: "<c-u>"
    scrollDownMain-alt1: "<c-d>"
    return: "<c-c>"
