os:
  editcommand: "nvim"
  opencommand: "nvim {{filename}} > /dev/null"
  # edit: "{{editor}} --server $NVIM --remote-tab {{filename}}"
  edit: "nvim --server $NVIM --remote-tab {{filename}}"

keybinding:
  universal:
    scrollUpMain-alt1: "<c-u>"
    scrollDownMain-alt1: "<c-d>"
